### ISSUE TITLE
Statistic page for sedekiq web UI

### ISSUE THREAD

**Issue by davydovanton** [travis-ci/travis-sidekiqs#5]
Hello all!
I created [plugin for sidekiq](https://github.com/davydovanton/sidekiq-statistic) which provide display more information about your workers and job. Also you can check [heroku application](https://sidekiq-history-gem.herokuapp.com/sidekiq/statistic) to see how it looks.
Therefore I want add this plugin to your repository, what do you think it'll good for travis?

**Comment by roidrage** [comment]
Hey @davydovanton, thanks for opening this issue, and congratulations on the plugin.

We're tracking all kinds of metrics and statistics for our Sidekiq usage in Librato, which is our central place to track and visualize that data. We don't use the Sidekiq console very often, so I'm not sure the plugin is going to be useful for us at this point.

Thank you!

**Comment by davydovanton** [comment]
okay, thanks for answer @roidrage :+1:
